### ISSUE TITLE
Show Series (Collection) Description on Record (MediaObject) Page

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/mlavalon#110]
Done When:
'Series Description' is displayed on catalog#show page, if data was entered for 'Series Description'.

**Comment by singlesoliloquy** [comment]
@foglabs for https://avalon2.wgbh.org/media_objects/zk51vg82g I'm looking at series description and it's kind of weird. Like in the Summary, we have PROGRAM DESCRIPTION: Series Description: Say Brother etc.
