### ISSUE TITLE
Add 'thumbnail_offset' and 'poster_offset' to MarsIngest machinery

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/mlavalon#114]
Because:
The Avalon Ingest API supports two fields that we didn't cover in MarsIngests:
thumbnail_offset
poster_offset

which control the time from which thumbnails are generated in `ExtractStillJob`

Done When:
-The Ingest CSV Template contains the new columns for these two fields
-The fields are added to MarsManifest header lists
-The fields are validated for the form "0:02" (in seconds)
-The fields are added to MarsIngestItem's API field mapping

**Comment by singlesoliloquy** [comment]
Good to go.
