### ISSUE TITLE
Unified Note/Note Type Columns In Ingest Sheet

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/mlavalon#119]
Because:
It's onerous to require "Note", "Note Type" sequential columns for various note types, so we want to use one column for each instances of a given note type.

Done When:

-The ingest sheet accepts "Item Type", "Content Type", "Technical Notes" as repeatable columns
-MarsManifest looks for these individual note type column names instead of note/note_type
-MarsIngestItem maps occurrences of these note columns to correct ingest API fields

**Comment by singlesoliloquy** [comment]
Good to go.
