### ISSUE TITLE
Add benchmark scripts

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#12]
### Because...
... we want to get some speed tests on Avalon in production like environment early on.

### Done when

We can run benchmarks on production.

### Steps / Questions

1. Add benchmark code (2 files) to code base
2. Run through a deployment

* **???** - How do we setup CI / CD?

**Comment by sroosa** [comment]
@afred can you put an update on this work here, and then close the ticket if it's done.

**Comment by afred** [comment]
First run of benchmarks succeeded.

**Results:** https://docs.google.com/spreadsheets/d/1indTK4U-gyqBq0TG3sX0T3fxMURYy8Rm_YgUvf5lMHE/edit?usp=sharing
