### ISSUE TITLE
Unified Input Columns for 'Other Identifier' type: value field pairs

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/mlavalon#121]
Because:
We want to make the Mars Ingest CSV as convenient as possible, and Peter/Rebecca want to rename a Other Identifier controlled-voc value ('Video Recording Identifier') to 'MLA Barcode'

Done When:
-As with note and note_type data, input data can be input in one column: 'MLA Barcode'
-and is mapped to 'other_identifier_type': 'videorecording identifier', 'other_identifier': <barcode value> by the ingest

**Comment by singlesoliloquy** [comment]
@foglabs-zen is this on the ingest sheet and not something I can QA on the site?
