### ISSUE TITLE
Spinning icon on Collections page

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/mlavalon#177]
**Describe the bug**
When a user clicks on the Collections tab, the screen they see just shows a spinning icon.

**To Reproduce**
1. Go to [https://avalon2.wgbh.org/collections](https://avalon2.wgbh.org/collections)
2. See the spinning icon and feel sadness.

**Expected behavior**
A user should be taken to a working collections page or the menu item should be removed.

**Additional context**
Our collections something that will work for our use case?

**Comment by singlesoliloquy** [comment]
Cors header

**Comment by jasoncorum** [comment]
Seeing this now on https://avalon.wgbh.org/collections and not https://avalon2.wgbh.org/collections

**Comment by jasoncorum** [comment]
There was some confusion in the ConfigMaps about using avalon v avalon2 that I seem to have sorted out, but based on how the setup was configured, it really looked like avalon-production was set up to be the avalon of record, now. going to confirm that before closing.
