### ISSUE TITLE
When a user creates a playlist they receive an error the page does not exist

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/mlavalon#178]
**Describe the bug**
Users get an error when they create a playlist

**To Reproduce**
1. Go to Playlists
2. Click on Create Playlist.
3. Make a playlist, then save and get an error.
Error URL [https://avalon2.wgbh.org/playlists/5](https://avalon2.wgbh.org/playlists/5)

**Expected behavior**

**Screenshots**
![Screen Shot 2021-01-13 at 10.28.20 AM.png](https://images.zenhubusercontent.com/5e5e7f2e572e74e6537e269f/6870619c-693d-4345-a77c-24c018bba4c6)

Also, if a playlist is created in Avalon2 it shows up in Avalon.

**Comment by singlesoliloquy** [comment]
Configuration error.

**Comment by jasoncorum** [comment]
I think this was related to #177. Tested after making the changes in the ConfigMap and that seems to have sorted this out too.
