### ISSUE TITLE
Creator and Contributors should show up on item records

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/mlavalon#185]
**Is your feature request related to a problem? Please describe.**
Creator and Contributors aren't showing up on item records.

**Describe the solution you'd like**
It would be useful for Creator and Contributors to have their own label and values display as metadata for the item records.

**Comment by jasoncorum** [comment]
@singlesoliloquy - wait, is this done? I'm seeing contributors here: https://avalon.wgbh.org/media_objects/1n79h439x.

**Comment by singlesoliloquy** [comment]
@jasoncorum for https://avalon.wgbh.org/media_objects/x920fx181 does it just not have that data?

**Comment by jasoncorum** [comment]
Confirmed that this record did not have creators or contributors included in the ingest CSV: https://avalon.wgbh.org/media_objects/x920fx181

Other records are displaying creators and contributors: https://avalon.wgbh.org/media_objects/hd76s021m.
