### ISSUE TITLE
Test using Ingest API to ingest metadata with media on WGBH Object Store

### ISSUE THREAD

**Issue by sroosa** [WGBH-MLA/mlavalon#2]
**Done when:**

- [x] figure out a login
- [ ] figure out curl URL, params, and body to POST objects
- [ ] Put together a sample ingest package
- [x] Demo individual ingests

**Comment by afred** [comment]
superseded by CSV ingest, through ingest API, streaming video from public S3.

additional tickets have been created to advance work toward streaming from object store: #45
