### ISSUE TITLE
Get local development and test environments running using Docker

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#41]
### Because
We need dev environments for TDD, debugging, safely resetting data, fast debug cycle, and all the other reasons why sane devs don't develop on production/staging environments.

### Background
We initially focused on getting Mlavalon up in a production-like environment to get flush out any potential costly production environment roadblocks like we've seen with other Fedora-based web apps. In so doing, neglected to keep our dev/test environments up to date.

### Done when
* Dev environments can be brought up with Docker compose
* Test environments can be brought up using Docker compose
* Tests pass.

**Comment by sroosa** [comment]
Done!!!
