### ISSUE TITLE
QUESTION: How do we steam video from object store

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#45]
### Because
For demo, we're streaming out of a completely public S3 bucket. Apparently ObjectStore requires signed URLs.

### Done when
The following questions have been answered:
* What is needed for streaming video from object store?
* What are the steps needed to make it happen?
* Tickets are created for doing ☝️ .

**Comment by sroosa** [comment]
We did this with a bucket policy whitelisting a fake domian we gave to the HLS streaming container.
