### ISSUE TITLE
Define mapping of MARS / QC database fields to Avalon fields

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#61]
### Because
Imports into Avalon will be comprised of metadata coming from MARS and the QC (quality control) databases.

The Avalon ingest will be refactored to handle data coming from these databases.

### Done when
There is a documented mapping of fields from MARS _and_ the QC database to fields that can be imported into the Avalon ingest API.

**Comment by foglabs-zen** [comment]
https://docs.google.com/spreadsheets/d/1tRi8mwqsWH9o3vnH5tk5Steofl5JXfjf4gcLKAW_27c/edit#gid=0

**Comment by singlesoliloquy** [comment]
Updated [https://docs.google.com/spreadsheets/d/1VSiZ-XtGn1qKoc_8UkGdRqobk25cisG1Z3Cn1Orz7yY/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1VSiZ-XtGn1qKoc_8UkGdRqobk25cisG1Z3Cn1Orz7yY/edit?usp=sharing)
