### ISSUE TITLE
Set thumbnails when ingesting records

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#62]
### Because
When records are ingested, there is currently no default thumbnail generated. Instead records display a placeholder image, which we do not want.

### Done when
Newly ingested records show a real thumbnail rather than a placeholder image.

**Comment by singlesoliloquy** [comment]
@jasoncorum is this the same your thumbnail ticket?

**Comment by afred** [comment]
Closed by #117 

Specifically, we have a lot of records that don't provide the duration of a video, and the thumbnail offset was being validated against those non-existent values and failing. To fix, this PR which deals with ingest sets the duration (if not present) to an arbitrarily high number so that validating the `thumbnail_offset` does not fail due to being out of range. A bit of a hack for sure, but also trying to leverage existing Avalon code.... the perpetual OSS trade off.
