### ISSUE TITLE
QUESTION: What is the best way to set thumbnails on ingest?

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#63]
### Background
We want records to have actual thumbnails, but there are too many records to set them all manually.

**Q:** Can we give Avalon a default timecode with which it automatically generates a thumbnail? This would be ideal.
**A:**

**Q:** Can we give Avalon ingest an existing URL to a thumbnail? This would mean generated the thumbnails before ingest, probably via FFMPEG plugin for Object Store (Rebecca mentioned that this exists).
**A:**

### Done when
We have a well-defined method for ingesting thumbnails for each record.

**Comment by singlesoliloquy** [comment]
First part is done.
