### ISSUE TITLE
BUG: "Create Thumbnail" button in the media player not working

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#64]
### To replicate
1. Navigate to a record's details page (for which the user has access to edit).
1. Click the Camera icon in the lower right corner of the player, with alt text "Create Thumbnail".
![image](https://user-images.githubusercontent.com/1507490/74799180-d54a9780-529d-11ea-9a55-eebf82d62ccb.png)
1. In the following modal, click "Update Poster Image"

### Expected behavior
It updates the poster image (i.e. the thumbnail).

### Actual behavior
The modal has a broken image, and clicking "Update Poster Image" has no effect.
![image](https://user-images.githubusercontent.com/1507490/74799419-73d6f880-529e-11ea-89cf-2decffb8e95e.png)

### Background
This may be as easy as ensuring ImageMagick is properly installed, so start there.

Also, I assume that Avalon considers "Poster Image" (what the player displays before playing) and the "Thumbnail" (what is shown in search results) is the same thing, but should verify this.

**Comment by jasoncorum** [comment]
Same as #65
