### ISSUE TITLE
BUG: Cannot manually set thumbnail from timecode when editing records

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#65]
### To reproduce
1. Navigate to a record's details page.
1. Click "Edit" button.
1. Click "Mange file(s)" option in the left menu.
1. In the "Associated Files" section, set the Thumbnail timecode to something new.
1. Click "Save"

### Expected Result
Avalon generates a new thumbnail based on the timecode, and uses that thumbnail for the record in search results.

### Actual result
You get a error:
![image](https://user-images.githubusercontent.com/1507490/74799010-61a88a80-529d-11ea-97d7-dba91c6858f5.png)

### Background
This may be due to missing or misconfigured dependencies like ImageMagick and/or FFMPEG

**Comment by jasoncorum** [comment]
Setting a duration on a Masterfile associated with a MediaObject on https://avalon.wgbh.org fixed the issue.
