### ISSUE TITLE
Create MarsIngestItem model, migration, and factory

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#86]
### Because
This is how we track the status of the individual jobs responsible for making Ingest API requests during a Mars Ingest.

### Done when
- [ ] db migrations are created
- [ ] validates Mars Manifest Row data
- [ ] validates status as one of: `enqueued`, `processing`, `failed`, `succeeded`
- [ ] belongs to Mars Ingest
- [ ] has a factory

### Depends on
#85 #82

**Comment by foglabs-zen** [comment]
whoops!
