### ISSUE TITLE
Create MarsIngestItemJob

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/mlavalon#87]
### Because
This job will allow concurrency of making POST and PUT requests to the Avalon Ingest API, and updating the status (and other fields) of a corresponding MarsIngestItem record in the database.

### Background
Follow [mperham's best practices](https://github.com/mperham/sidekiq/wiki/Best-Practices).

To **keep parameter simple and small**, pass the job an existing `MarsIngestItem#id` (or Global ID if that's what we end up doing). This means that the `MarsIngestItem` record should have all necessary information (including the raw row data) required to insert or update the `MediaObject`.

To **make the job idempotent**, it should use a "find or create" pattern based on the existence, or non-existence, of a MediaObject ID or a Bibliographic ID.

To **make the job transactional**, it should utilize the `rescue_from` block to rollback any changes that may have been partially completed during a failed `perform` method.

To **embrace concurrency**, it should use the "find or create" pattern _in addition to_ a retry strategy, such that if a race condition leads to a create operation failing (due to "FIELD must be unique"), then the job is retried, and the subsequent try succeeds in finding the record that was created by the other job.

### Done when
Specs pass for job that tests the following:
- [x] the `after_enqueue` callback updates `MarsIngestItem#status` to `enqueued`.
- [ ] the `before_perform` callback updates `MarsIngestItem#status` to `processing`.
- [x] the `after_perform` callback updates the `MarsIngestItem#status` to `succeeded` when the response from the Ingest API indicates a success.
- [x] the `after_perform` callback updates the `MarsIngestItem#status` to `failed` when the response from the Ingest API indicates a failure.
- [x] the `rescue_from` callback updates
   - [x] `MarsIngestItem#status` to `failed`
   - [x] `MarsIngestItem#errors` to whatever the errors are.
     * _NOTE:_ from AMS experience, it may be worth it to store serialized JSON here so that we can track a succinct error message for display, plus a stack trace for post mortem. 
- [ ] When successful, the `MediaObject` is actually ingested! :)

### Depends on
#86

**Comment by jasoncorum** [comment]
This is ready, but we will still have to test that a MediaObject gets created with our mars_ingest controller spec.
